name: Machine Learning CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-save-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5 
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn

    - name: Run MLflow Project (Training)
      env:
        # Menetapkan lokasi tracking ke direktori lokal di runner
        MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/mlruns"
      run: |
        # Menjalankan training melalui MLflow Project
        # --env-manager local digunakan agar menggunakan library yang sudah diinstall di atas
        mlflow run MLProject/ --entry-point main --env-manager local

    - name: Archive Model Artifacts
      # Langkah ini akan menyimpan folder mlruns (berisi model.pkl, params, metrics)
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifacts
        path: mlruns/
        retention-days: 7 # Opsional: menyimpan file selama 7 hari saja